Repository AdarshAddee/Hacktoberfest2022_for_Beginers, pull requests merged in 2022-10, with the labels that each got.

#51 Count Number Of Paths To Reach From 1 To N Problem
  CONTRIBUTORS.md
  Java/CountingTheNumberOfPathsToReachFrom1ToN.java
Labels: hacktoberfest

#53 added Kadane's Algorithm in C++
  C++/Kadanes_Algorithm.cpp
  CONTRIBUTORS.md
Labels: hacktoberfest

#52 Added print 1 10 100 without numbers
  CONTRIBUTORS.md
  Python/Print 1 to 100 without numbers.py
  Python/common_factor.py
Labels: hacktoberfest

#18 Create loading_on_python.py
  Python/loading_on_python.py
Labels: hacktoberfest

#29 Added code of C++
  C++/Pow.cpp
  CONTRIBUTORS.md
Labels: hacktoberfest

#25 Create Search_a_2D_Matrix.cpp
  C++/Search_a_2D_Matrix.cpp
Labels: hacktoberfest22

#55 added number guessing game
  Python/number guesser game.py
Labels: hacktoberfest22

#57 Added xor Linked List and trie
  C++/Trie.cpp
  C++/XOR LL.cpp
Labels: hacktoberfest22

#58 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest22

#62 Added BlackJack Capstone Game in Python
  CONTRIBUTORS.md
  Python/BlackjackCapstoneGame.py
Labels: hacktoberfest22

#64 reverse integer program
  C++/Reverse_integer.cpp
Labels: hacktoberfest22

#66 Created intersection-of-two-linked-lists.cpp
  C++/intersection-of-two-linked-lists.cpp
Labels: hacktoberfest22

#67 Change image from webp to png
  Python/webp to png.py
Labels: hacktoberfest22

#68 hacktoberfest-2022
  CONTRIBUTORS.md
  Python/GUI_calculator.py
Labels: hacktoberfest22

#69 Added an number pattern
  Python/Numberpattern.py
Labels: hacktoberfest22

#72 added string reverser
  PHP/stringReverser.php
Labels: hacktoberfest22

#73 Question from CodeChef
  Java/CodeChef/q1.java
Labels: hacktoberfest22

#71 Create Search in Rotated Sorted Matrix
  C++/Search in Rotated Sorted Matrix
Labels: hacktoberfest22

#74 Taylor Series
  C/Taylor Series.c
Labels: hacktoberfest22

#75 Create create_segment_tree.cpp
  C++/create_segment_tree.cpp
Labels: hacktoberfest22

#157 Snakegame in python
  Python/snakegame.py
Labels: HACKTOBERFEST-ACCEPTED

#226 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#224 number with Dart
  CONTRIBUTORS.md
  Dart/numbers.dart
  README.md
Labels: HACKTOBERFEST-ACCEPTED

#215 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#214 Added InsertionSort.java file
  CONTRIBUTORS.md
  Java/InsertionSort.java
Labels: HACKTOBERFEST-ACCEPTED

#206 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#230 Added Quick Sort in java.
  CONTRIBUTORS.md
  Java/QuickSort.java
Labels: HACKTOBERFEST-ACCEPTED

#199 Added Tic Tac Toe game in Python
  CONTRIBUTORS.md
  Python/tic_tac_toe_game.py
Labels: HACKTOBERFEST-ACCEPTED

#192 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#186 Checkpass.py
  Python/checkpass.py
Labels: HACKTOBERFEST-ACCEPTED

#84 Selection_sort.c
  C/selection_sort.c
Labels: HACKTOBERFEST-ACCEPTED

#106 Steganography.py
  Python/Steganography.py
Labels: HACKTOBERFEST-ACCEPTED

#116 Create Power_of_2.cpp
  C++/Power_of_2.cpp
Labels: HACKTOBERFEST-ACCEPTED

#137 Added Merge Sort Algorithm cpp
  C++/Merge_sort.cpp
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#121 created factorial program in cpp
  C++/factorialprogram.cpp
Labels: HACKTOBERFEST-ACCEPTED

#123 Implement Bubble Sort
  C/BubbleSort.c
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#148 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#161 Update the CONTRIBUTORS.md and add the counting sort.cpp file
  C++/Counting_sort.cpp
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#170 Created connected components cpp
  C++/Connected_components.cpp
Labels: HACKTOBERFEST-ACCEPTED

#169 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#260 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#239 update: contributor :rocket:
  C++/ComparingTwoFractions.cpp
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED

#254 Create hourglass_pattern.py
  Python/hourglass_pattern.py
Labels: HACKTOBERFEST-ACCEPTED

#244 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: HACKTOBERFEST-ACCEPTED
